services:
  firefox:
    image: lscr.io/linuxserver/chromium:latest
    container_name: wa-kube-1
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - CHROME_CLI=https://web.whatsapp.com/ #optional
      - CUSTOM_USER=user
      - PASSWORD=<password>
    volumes:
      - ~/data-docker/:/config
    ports:
      #- 3000:3000 ## disable http unsecure port
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
