version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: 'host'
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./docker-data/nginx-proxy:/data
      - ./docker-data/nginx-proxy/letsencrypt:/etc/letsencrypt
